//首页
var tmpl_loginStatus = ''
+    '{{if id}}'
+    	'<a class="logined" href="mine.html">'
+			'<div class="prt" {{if photo}}style="background-image:url({{photo}});"{{/if}}></div>'
+    	'</a>'
+    '{{else}}'
+    	'<a href="userLogin.html">'
+			'<i class="sprite icon-mine"></i>'
+    	'</a>'
+    '{{/if}}';

var tmpl_indexBnr = ''
+    '{{each body}}'
+		'<li style="background-image:url({{$value.img}});"></li>'
+    '{{/each}}';

var tmpl_hotThemes = ''
+    '{{each body}}'
+    	'<li data-pid="{{$value.pid}}">'
+    		'<a href="pdtDetail.html?pid={{$value.pid}}">'
+    			'<div class="fullImg lazy" data-original="{{$value.size_img2}}"></div>'
+    			'<p class="price">¥{{$value.price}}/起</p>'
+    			'<div class="cnt">'
+    				'<h5 class="tit">{{$value.pname}}</h5>'
+    				'<p class="intro">「 {{$value.description}}」</p>'
+    			'</div>'
+    		'</a>'
+    	'</li>'
+    '{{/each}}';

var tmpl_hotDest = ''
+    '{{each body}}'
+    	'<li>'
+    		'<a href="pdtList.html?destination={{$value.id}}">'
+    			'<div class="fullImg lazy" data-original="{{$value.img}}"></div>'
+    			'<h5 class="tit">{{$value.cityName}}</h5>'
+    		'</a>'
+    	'</li>'
+    '{{/each}}';

var tmpl_hotService = ''
+    '{{each body}}'
+    	'<li>'
+    		'<a href="pdtDetail.html?pid={{$value.pid}}">'
+    			'<div class="img lazy" data-original="{{$value.size_img2}}"></div>'
+    			'<div class="intro">{{$value.pname}}</div>'
+    		'</a>'
+    	'</li>'
+    '{{/each}}';

//我的麦味
var tmpl_mineMenu = ''
+    '<div class="item item1">'
+	 	'{{if id}}'
+    		'<a class="f-box" href="mineInfo.html">'
+    			'<div class="prt">'
+	 				'{{if photo}}'
+    					'<div class="prtView" style="background-image:url({{photo}});"></div>'
+    				'{{/if}}'
+    			'</div>'
+    			'<label>{{realName}}</label>'
+    			'<span class="arrow"></span>'
+    		'</a>'
+    	'{{else}}'
+    		'<a class="f-box" href="userLogin.html">'
+    			'<div class="prt" ></div>'
+    			'<label>点我<span class="color4">登录</span></label>'
+    			'<span class="arrow"></span>'
+    		'</a>'
+    	'{{/if}}'
+    '</div>'
+    '<div class="item">'
+	 	'{{if id}}'
+    	'<a class="f-box" href="mineOrders.html">'
+    	'{{else}}'
+    	'<a class="f-box" href="userLogin.html">'
+    	'{{/if}}'
+    		'<label>我的订单</label>'
+    		'<span class="textRt f-flex">查看所有订单</label>'
+    		'<span class="arrow"></span>'
+    	'</a>'
+    '</div>'
+    '<div class="item">'
+	 	'{{if id}}'
+    	'<a class="f-box" href="mineCollect.html">'
+    	'{{else}}'
+    	'<a class="f-box" href="userLogin.html">'
+    	'{{/if}}'
+    		'<label>我的收藏</label>'
+    		'<span class="arrow"></span>'
+    	'</a>'
+    '</div>'
+    '<div class="item">'
+    	'<a class="f-box" href="about.html">'
+    		'<label>关于我们</label>'
+    	'</a>'
+    '</div>'
+    '<div class="item">'
+    	'<a class="f-box" href="tel:4006456701">'
+    		'<label>致电小麦</label>'
+    		'<span class="textCr f-flex">400 - 645 - 6701</label>'
+    	'</a>'
+    '</div>'
+    '<div class="qr">'
+    	'<img src="images/qr.jpg" />'
+    	'<p class="text">麦味服务号</p>'
+    '</div>'
+	 '{{if id}}'
+    '<a class="logout" id="logout">退出登录</a>'
+    '{{/if}}';

var tmpl_mineInfo = ''
+	 '<div class="item">'
+	 	'<form id="portraitForm" method="post" enctype="multipart/form-data">'
+	 		'<a class="prtLink f-box">'
+	 			'<label class="f-flex">上传头像</label>'
+	 			'<span class="arrow"></span>'
+	 			'<div class="prt imgUpload">'
+	 				'<div class="picPreview" id="picPreview" {{if photo}}style="background-image:url({{photo}});"{{/if}}></div>'
+	 				'<input class="fileInput" id="picFile" type="file" name="uploadList" accept="image/*">'
+	 			'</div>'
+	 		'</a>'
+	 	'</form>'	
+	 	'<a class="f-box" href="mineEditName.html">'
+	 		'<label>用户名</label>'
+	 		'<span class="arrow"></span>'
+	 		'<span class="textRt f-flex">{{realName}}</label>'
+	 	'</a>'
+	'</div>'
+	'<div class="item">'
+		'<a class="f-box" href="mineEditPhone.html">'
+			'<label>手机号</label>'
+			'<span class="arrow"></span>'
+	 		'{{if tel}}'
+				'<span class="textRt f-flex">{{tel}}&nbsp;&nbsp;&nbsp;已绑定</label>'
+    		'{{else}}'
+				'<span class="textRt f-flex">未绑定</label>'
+    		'{{/if}}'
+		'</a>'
+	'</div>'
+	'<div class="item">'
+		'<a class="f-box" href="mineEditPwd.html">'
+			'<label>修改密码</label>'
+			'<span class="arrow"></span>'
+		'</a>'
+	'</div>'

//产品列表
var tmpl_product = ''
+    '{{each list}}'
+    	'<li data-pid="{{$value.pid}}">'
+    		'<a href="pdtDetail.html?pid={{$value.pid}}">'
+    			'<div class="fullImg lazy" data-original="{{$value.size_img2}}"></div>'
+    			'<p class="price">¥{{$value.start_price}}/起</p>'
+    			'<div class="cnt">'
+    				'<h5 class="tit"><span class="color1">【{{$value.countryName}} {{$value.cityName}}】</span>{{$value.pname}}</h5>'
//+    				'<p class="intro"></p>'
+ 					'<div class="info f-box">'
+ 						'<div class="label f-flex">{{$value.tags}}</div>'
+ 					'</div>'
+    			'</div>'
+    		'</a>'
+    	'</li>'
+    '{{/each}}';

//我的收藏列表
var tmpl_favorite = ''
+    '{{each list}}'
+    	'<li data-pid="{{$value.pid}}">'
+    		'<a href="pdtDetail.html?pid={{$value.pid}}">'
+    			'<div class="fullImg lazy" data-original="{{$value.size_img2}}"></div>'
+    			'<p class="price">¥{{$value.start_price}}/起</p>'
+    			'<div class="cnt">'
+    				'<h5 class="tit"><span class="color1">【{{$value.countryName}} {{$value.cityName}}】</span>{{$value.pname}}</h5>'
//+    				'<p class="intro"></p>'
+ 					'<div class="info f-box">'
+ 						'<div class="label f-flex">{{$value.tags}}</div>'
+ 					'</div>'
+    			'</div>'
+    		'</a>'
+    		'<button class="operateBtn sprite"></button>'
+    	'</li>'
+    '{{/each}}';

//分类下拉列表
var tmpl_dropdown_theme = ''
+    '{{each themeOptions}}'
+		'{{if $value.selected}}'
+    		'<li class="am-active"><a href="{{$value.key}}">{{$value.value}}</a></li>'
+     	'{{else}}'
+    		'<li><a href="{{$value.key}}">{{$value.value}}</a></li>'
+     	'{{/if}}'
+    '{{/each}}';
var tmpl_dropdown_destination = ''
+    '{{each destinationOptions}}'
+		'{{if $value.selected}}'
+    		'<li class="am-active"><a href="{{$value.key}}">{{$value.value}}</a></li>'
+     	'{{else}}'
+    		'<li><a href="{{$value.key}}">{{$value.value}}</a></li>'
+     	'{{/if}}'
+    '{{/each}}';
var tmpl_dropdown_services = ''
+    '{{each serviceOptions}}'
+		'{{if $value.selected}}'
+    		'<li class="am-active"><a href="{{$value.key}}">{{$value.value}}</a></li>'
+     	'{{else}}'
+    		'<li><a href="{{$value.key}}">{{$value.value}}</a></li>'
+     	'{{/if}}'
+    '{{/each}}';
var tmpl_dropdown_orderby = ''
+    '{{each orderbyOptions}}'
+		'{{if $value.selected}}'
+    		'<li class="am-active"><a href="{{$value.key}}">{{$value.value}}</a></li>'
+     	'{{else}}'
+    		'<li><a href="{{$value.key}}">{{$value.value}}</a></li>'
+     	'{{/if}}'
+    '{{/each}}';

//分类筛选面板
var tmpl_filtrate_serve = ''
+    '{{each typeOptions}}'
+		'{{if $index == 0}}'
+    		'<a class="am-active" href="{{$value.key}}">{{$value.value}}</a>'
+     	'{{else}}'
+    		'<a href="{{$value.key}}">{{$value.value}}</a>'
+     	'{{/if}}'
+    '{{/each}}';
var tmpl_filtrate_sort = ''
+    '{{each orderbyOptions}}'
+		'{{if $index == 0}}'
+    		'<a class="am-active" href="{{$value.key}}">{{$value.value}}</a>'
+     	'{{else}}'
+    		'<a href="{{$value.key}}">{{$value.value}}</a>'
+     	'{{/if}}'
+    '{{/each}}';
var tmpl_filtrate_dest = ''
+    '{{each destinationOptions}}'
+		'{{if $index == 0}}'
+    		'<a class="am-active" href="{{$value.key}}">{{$value.value}}</a>'
+     	'{{else}}'
+    		'<a href="{{$value.key}}">{{$value.value}}</a>'
+     	'{{/if}}'
+    '{{/each}}';

var tmpl_productBnr = ''
+    '{{each size_img1.split(",")}}'
+		'<li style="background-image:url({{$value}});"></li>'
+    '{{/each}}';


//我的订单列表
var tmpl_order = ''
+    '{{each list}}'
+		'{{if $value.del_flg == "0"}}'
+    	'<li class="orderItem" data-pid="{{$value.routeJson.pdt_id}}">'
+    		'<a class="link" href="mineOrderDetail.html?orderNo={{$value.order_no}}">'
+				'{{if $value.status == 1}}'
+    			'<p class="state">待付款</p>'
+				'{{else if $value.status == 2}}'
+    			'<p class="state">待处理</p>'
+				'{{else if $value.status == 3}}'
+    			'<p class="state">待付尾款</p>'
+				'{{else if $value.status == 4}}'
+    			'<p class="state">待出行</p>'
+				'{{else if $value.status == 5}}'
+    			'<p class="state">已完成</p>'
+				'{{else if $value.status == 6}}'
+    			'<p class="state">出行中</p>'
+				'{{else if $value.status == 8}}'
+    			'<p class="state">支付中</p>'
+				'{{else if $value.status == 9}}'
+    			'<p class="state">已退款</p>'
+   			'{{/if}}'
+    			'<p class="name f-toe">{{$value.order_nm}}</p>'
+    			'<p class="dest">{{$value.routeJson.pdt_address}}</p>'
+    			'<div class="cnt1 f-box">'
+    				'<div class="img">'
+    					'<div class="pic" style="background-image:url({{$value.routeJson.pdt_pic}});" />'
+						'{{if $value.routeJson.pdt_type == 0}}'
+    					'<p class="type">套餐</p>'
+						'{{else if $value.routeJson.pdt_type == 1}}'
+    					'<p class="type">酒店</p>'
+						'{{else if $value.routeJson.pdt_type == 2}}'
+    					'<p class="type">别墅</p>'
+						'{{else if $value.routeJson.pdt_type == 3}}'
+    					'<p class="type">交通</p>'
+						'{{else if $value.routeJson.pdt_type == 4}}'
+    					'<p class="type">娱乐</p>'
+   					'{{/if}}'
+    				'</div>'
+    				'<div class="info">'
+    					'{{if $value.routeJson.time_start}}'
+							'{{if $value.routeJson.pdt_type == 1 || $value.routeJson.pdt_type == 2}}'
+    						'<p>入住日期：{{$value.routeJson.time_start}}</p>'
+     						'{{else}}'
+   						'<p>出发日期：{{$value.routeJson.time_start}}{{if $value.routeJson.time_detail}}&nbsp;&nbsp;{{$value.routeJson.time_detail}}{{/if}}</p>'
+   						'{{/if}}'
+   					'{{/if}}'
+    					'{{if $value.routeJson.time_end}}'
+							'{{if $value.routeJson.pdt_type == 2}}'
+    						'<p>退房日期：{{$value.routeJson.time_end}}</p>'
+   						'{{/if}}'
+   					'{{/if}}'
+   					'{{if $value.routeJson.time_days && $value.routeJson.pdt_type == 2}}'
+							'<p>天数：{{$value.routeJson.time_days}}</p>'
+   					'{{/if}}'
+    					'<p>数量：'
+    					'{{if $value.routeJson.pdt_type == 2}}'
+	 						'{{each $value.routeJson.order_data}}'
+   						'{{$value.tname}} <i class="am-icon-times"></i> {{$value.num}}&nbsp;&nbsp;&nbsp;'
+	 						'{{/each}}'
+    					'{{else if $value.routeJson.pdt_type == 3}}'
+	 						'{{each $value.routeJson.order_data}}'
+   						'{{$value.tname}} <i class="am-icon-times"></i> {{$value.num}}&nbsp;&nbsp;&nbsp;'
+	 						'{{/each}}'
+    					'{{else}}'
+	 						'{{each $value.routeJson.order_data}}'
+   						'{{$value.tname}} <i class="am-icon-times"></i> {{$value.num}}&nbsp;&nbsp;&nbsp;'
+	 						'{{/each}}'
+   					'{{/if}}'
+    					'</p>'
+    				'</div>'
+    			'</div>'
+    			'<div class="cnt2 f-box">'
+    				'<p class="f-flex f-otvc">下单时间：{{$value.ctdt | dateFormat:"yyyy-MM-dd"}}</p>'
+    				'<p class="total f-flex f-otvc">合计：<span class="color2">¥ {{$value.amount}}</span></p>'
+    			'</div>'
+    		'</a>'							
+    		'<div class="orderOperate f-box">'
+				'{{if $value.status == 1}}'
+					'<a class="btn btnH orderCancel" data-orderno="{{$value.order_no}}" href="/mobile/cancelOrder.do">取消订单</a>'
+					'{{if $value.travelPartners}}'
+    				'<a class="btn btnH" href="orderTravellers.html?orderNo={{$value.order_no}}">编辑随行人</a>'
+    				'<a class="btn btnS" href="orderPay.html?orderNo={{$value.order_no}}">去付款</a>'
+    				'{{else}}'
+    				'<a class="btn btnH" href="orderTravellers.html?orderNo={{$value.order_no}}">添加随行人</a>'
+   				'{{/if}}'
+				'{{else if $value.status == 2}}'
+					'<a class="btn btnH" disabled="disabled">处理中...</a>'
+				'{{else if $value.status == 3}}'
+    				'<a class="btn btnH" href="orderTravellers.html?orderNo={{$value.order_no}}">编辑随行人</a>'
+					'<a class="btn btnS" href="orderPay.html?orderNo={{$value.order_no}}">去付尾款</a>'
+				'{{else if $value.status == 4}}'
+					'<a class="btn btnH orderRefund">申请退款</a>'
+				'{{else if $value.status == 5}}'
+					'<a class="btn btnH orderDelete" data-orderno="{{$value.order_no}}" href="/mobile/delmyorder.do">删除订单</a>'
+					'{{if $value.evaluateflg == "0"}}'
+					'<a class="btn btnS" href="pdtDetail.html?pid={{$value.routeJson.pdt_id}}#anchor_review">去评价</a>'
+   				'{{/if}}'
+				'{{else if $value.status == 6}}'
+					'<a class="btn btnS" disabled="disabled">出行中...</a>'
+				'{{else if $value.status == 8}}'
+					'<a class="btn btnS" disabled="disabled">支付中...</a>'
+				'{{else if $value.status == 9}}'
+					'<a class="btn btnH orderDelete" data-orderno="{{$value.order_no}}" href="/mobile/delmyorder.do">删除订单</a>'
+					'<a class="btn btnH" disabled="disabled">已退款</a>'
+   			'{{/if}}'
+    		'</div>'
+    	'</li>'
+    	'{{/if}}'
+    '{{/each}}';

//订单详情页
var tmpl_orderDetail = ''
+   '<div class="base">'
+   	'<p>订单编号：{{orderNo}}</p>'
+   	'<p>下单时间：{{ctdt | dateFormat:"yyyy-MM-dd hh:mm"}}</p>'
+   	'<p>订单备注：{{routeJson.remark}}</p>'
+   '</div>'
+   '<div class="orderItem" data-pid="{{routeJson.pdt_id}}">'
+   	'<a class="link" href="pdtDetail.html?pid={{routeJson.pdt_id}}">'
+   		'<p class="state"></p>'
+  			'<p class="name f-toe">{{orderNm}}</p>'
+   		'<p class="dest">{{routeJson.pdt_address}}</p>'
+   	'</a>'
+   	'<div class="cnt1 f-box">'
+   		'<a class="img" href="pdtDetail.html?pid={{routeJson.pdt_id}}">'
+    			'<div class="pic" style="background-image:url({{routeJson.pdt_pic}});" />'
+				'{{if routeJson.pdt_type == 0}}'
+    			'<p class="type">套餐</p>'
+				'{{else if routeJson.pdt_type == 1}}'
+    			'<p class="type">酒店</p>'
+				'{{else if routeJson.pdt_type == 2}}'
+    			'<p class="type">别墅</p>'
+				'{{else if routeJson.pdt_type == 3}}'
+    			'<p class="type">交通</p>'
+				'{{else if routeJson.pdt_type == 4}}'
+    			'<p class="type">娱乐</p>'
+   			'{{/if}}'
+   		'</a>'
+   		'<div class="info">'
+    			'{{if routeJson.time_start}}'
+					'{{if routeJson.pdt_type == 1 || routeJson.pdt_type == 2}}'
+    					'<p>入住日期：{{routeJson.time_start}}</p>'
+     				'{{else}}'
+   					'<p>出发日期：{{routeJson.time_start}}{{if routeJson.time_detail}}&nbsp;&nbsp;{{routeJson.time_detail}}{{/if}}</p>'
+   				'{{/if}}'
+   			'{{/if}}'
+    			'{{if routeJson.time_end}}'
+					'{{if routeJson.pdt_type == 2}}'
+    					'<p>退房日期：{{routeJson.time_end}}</p>'
+   				'{{/if}}'
+   			'{{/if}}'
+    			'{{if routeJson.time_days && routeJson.pdt_type == 2}}'
+    				'<p>天数：{{routeJson.time_days}}天</p>'
+   			'{{/if}}'
+   			'<p class="remark">{{routeJson.remark}}</p>'
+   		'</div>'
+   	'</div>'
+    	'{{if routeJson.pdt_type == 2}}'
+	 		'{{each routeJson.order_data}}'
+   			'<div class="cnt2 f-box">'
+   				'<div class="f-flex f-otvc">'
+   					'<p class="imp">{{$value.tname}}</p>'
+   					'<p class="fs20">单价¥{{$value.price}}（每幢）</p>'
+   				'</div>'
+   				'<p class="f-otvc">x{{$value.num}}幢,  x{{routeJson.time_days}}晚</p>'
+   				'<p class="f-flex f-otvc f-tar">¥{{$value.price*$value.num*routeJson.time_days}}</p>'
+   			'</div>'
+	 		'{{/each}}'
+    	'{{else if routeJson.pdt_type == 3}}'
+	 		'{{each routeJson.order_data}}'
+   			'<div class="cnt2 f-box">'
+   				'<div class="f-flex f-otvc">'
+   					'<p class="imp">{{$value.tname}}</p>'
+   					'<p class="fs20">单价¥{{$value.price}}（每辆）</p>'
+   				'</div>'
+   				'<p class="f-otvc">x{{$value.num}}辆</p>'
+   				'<p class="f-flex f-otvc f-tar">¥{{$value.price*$value.num}}</p>'
+   			'</div>'
+	 		'{{/each}}'
+    	'{{else}}'
+	 		'{{each routeJson.order_data}}'
+   			'<div class="cnt2 f-box">'
+   				'<div class="f-flex f-otvc">'
+   					'<p class="imp">{{$value.tname}}</p>'
+   					'<p class="fs20">单价¥{{$value.price}}（每人）</p>'
+   				'</div>'
+   				'<p class="f-otvc">x{{$value.num}}人</p>'
+   				'<p class="f-flex f-otvc f-tar">¥{{$value.price*$value.num}}</p>'
+   			'</div>'
+	 		'{{/each}}'
+   	'{{/if}}'
+   	'<div class="cnt3">'
+   		'<p class="t1 f-tar">合计：<span class="color2 fs28">¥ {{amount}}</span></p>'
+   		'<p class="t2 f-tar fs20">（价格已含税）</p>'
+   	'</div>'
+   	'<div class="totalBar f-box">'
+   		'<div class="total color2">¥{{prepay}}</div>'
+   		'<div class="orderOperate f-flex f-box">'
+				'{{if status == 1}}'
+					'<a class="btn btnH orderCancel" data-orderno="{{orderNo}}" href="/mobile/cancelOrder.do">取消订单</a>'
+					'{{if travelPartners}}'
+    				'<a class="btn btnH" href="orderTravellers.html?orderNo={{orderNo}}">编辑随行人</a>'
+    				'<a class="btn btnS" href="orderPay.html?orderNo={{orderNo}}">去付款</a>'
+    				'{{else}}'
+    				'<a class="btn btnH" href="orderTravellers.html?orderNo={{orderNo}}">添加随行人</a>'
+   				'{{/if}}'
+				'{{else if status == 2}}'
+					'<a class="btn btnH" disabled="disabled">处理中...</a>'
+				'{{else if status == 3}}'
+    				'<a class="btn btnH" href="orderTravellers.html?orderNo={{orderNo}}">编辑随行人</a>'
+					'<a class="btn btnS" href="orderPay.html?orderNo={{orderNo}}">去付尾款</a>'
+				'{{else if status == 4}}'
+					'<a class="btn btnH orderRefund">申请退款</a>'
+				'{{else if status == 5}}'
+					'<a class="btn btnH orderDelete" data-orderno="{{orderNo}}" href="/mobile/delmyorder.do">删除订单</a>'
+					'{{if evaluateflg == "0"}}'
+					'<a class="btn btnS" href="pdtDetail.html?pid={{routeJson.pdt_id}}#anchor_review">去评价</a>'
+   				'{{/if}}'
+				'{{else if status == 6}}'
+					'<a class="btn btnS" disabled="disabled">出行中...</a>'
+				'{{else if status == 8}}'
+					'<a class="btn btnS" disabled="disabled">支付中...</a>'
+				'{{else if status == 9}}'
+					'<a class="btn btnH orderDelete" data-orderno="{{orderNo}}" href="/mobile/delmyorder.do">删除订单</a>'
+					'<a class="btn btnH" disabled="disabled">已退款</a>'
+   			'{{/if}}'
+   		'</div>'
+   	'</div>'
+   '</div>'
+   '<div class="box">'
+   	'<h5 class="tit">联系人信息</h5>'
+   	'<ul class="infoContacts">'
+   		'<li class="f-box">'
+   			'<label>姓名 ：</label>'
+   			'<p class="f-flex">{{routeJson.linkman_name}}</p>'
+   		'</li>'
+   		'<li class="f-box">'
+   			'<label>手机 ：</label>'
+   			'<p class="f-flex">{{routeJson.linkman_phone}}</p>'
+   		'</li>'
+   		'<li class="f-box">'
+   			'<label>邮箱 ：</label>'
+   			'<p class="f-flex">{{routeJson.linkman_email}}</p>'
+   		'</li>'
+   	'</ul>'
+   '</div>';

//订单详情页随行人
var tmpl_orderDetailTvr = ''
+   '<div class="box">'
+   	'<h5 class="tit">旅客信息</h5>'
+    	'{{if body.length > 0}}'
+   	'<ul class="infoTravellers">'
+	 		'{{each body}}'
+   		'<li class="f-box">'
+   			'<p>{{$value.realName}} {{$value.customerName}}</p>'
+				'{{if $value.cardType == 1}}'
+   			'<p class="f-flex f-tar">身份证 ：{{$value.cardNumber}}</p>'
+				'{{else if $value.cardType == 2}}'
+   			'<p class="f-flex f-tar">护照号码 ：{{$value.cardNumber}}</p>'
+				'{{else if $value.cardType == 3}}'
+   			'<p class="f-flex f-tar">军人证 ：{{$value.cardNumber}}</p>'
+				'{{else if $value.cardType == 4}}'
+   			'<p class="f-flex f-tar">回乡证 ：{{$value.cardNumber}}</p>'
+				'{{else if $value.cardType == 5}}'
+   			'<p class="f-flex f-tar">台胞证 ：{{$value.cardNumber}}</p>'
+				'{{else if $value.cardType == 6}}'
+   			'<p class="f-flex f-tar">港澳通行证 ：{{$value.cardNumber}}</p>'
+				'{{else if $value.cardType == 7}}'
+   			'<p class="f-flex f-tar">户口簿 ：{{$value.cardNumber}}</p>'
+				'{{else if $value.cardType == 8}}'
+   			'<p class="f-flex f-tar">出生证明 ：{{$value.cardNumber}}</p>'
+				'{{else if $value.cardType == 9}}'
+   			'<p class="f-flex f-tar">其他证件 ：{{$value.cardNumber}}</p>'
+				'{{/if}}'
+   		'</li>'
+	 		'{{/each}}'
+   	'</ul>'
+   	'{{else}}'
+   	'<p class="f-tac" style="padding:40px 0 50px 0;">当前还没有添加任何随行人</p>'
+   	'{{/if}}'
+   '</div>';

//产品详情页
var tmpl_productBase = ''
+	 '{{if ptype == 2}}'
+    	'<h1 class="name">【{{map_address}}】{{pname}}</h1>'
+    '{{else}}'
+    	'<h1 class="name">{{pname}}</h1>'
+    '{{/if}}'
+    '<div class="badges">'
+    	'{{each tags.split("|")}}'
+    		'<span>{{$value}}</span>'
+    	'{{/each}}'
+    '</div>'
+    '<div class="f-box">'
+    	'<p class="f-flex collect">已收藏：<span id="markedTimes">{{markedTimes}}</span>次</p>'
+    	'<p class="f-flex price color2">¥<span class="fs32">{{start_price}}</span>/起</p>'
+    '</div>';

var tmpl_productEval = ''
/*+	 '{{if list.length <= 0}}'
+	 	'<p style="padding:20px 0 30px 0;text-align:center;">暂时没有任何评论</p>'
+    '{{else}}'
+	 	'<ul class="reviewList">'*/
+			'{{each list}}'
+	 			'<li>'
+	 				'<div class="prt lazy" data-original="{{$value.photo||\'images/prtDefault.jpg\'}}"></div>'
+	 				'<div class="info">'
+	 					'<p class="nick">{{$value.customerName || "匿名用户"}}</p>'
+	 					'<p class="time">{{$value.ctdt | dateFormat:"yyyy.MM.dd"}}</p>'
+	 					'<p class="cnt">{{$value.content || "他太懒了，没留下任何评价"}}</p>'
+	 				'</div>'	          					
+	 			'</li>'
+    		'{{/each}}';
/*+	 	'</ul>'
+    '{{/if}}';*/

var tmpl_productSche = ''
+	 '{{if body.length <= 0}}'
+	 	'<p style="padding:20px 0 30px 0;text-align:center;">无行程描述</p>'
+    '{{else}}'
+	 	'<div class="am-panel-group journeyPanel">'
+	 		'{{each body}}'
+	 			'<div class="am-panel">'
+	 				'<div class="am-panel-hd">'
+	      				'<h4 class="am-panel-title">• {{$value.tabs}} : {{$value.mapAddress}}</h4>'
+	    			'</div>'
+	    			'<div class="am-panel-collapse am-collapse">'
+	      				'<div class="am-panel-bd">{{$value.description}}</div>'
+	   				'</div>'
+  				'</div>'
+    		'{{/each}}'
+  	 	'</div>'
+    '{{/if}}';

var tmpl_productBook = ''
+	 '<a class="service f-flex f-otvc" href="tel:4006456701"><span class="icon sprite"></span>联系客服</a>'
+	 '{{if ptype == "0"}}'
+	 	'<a class="next" id="pdtBook" href="orderForm_meal.html">立即预定</a>'
+    '{{else if ptype == "1"}}'
+	 	'<a class="next" id="pdtBook" href="orderForm_hotel.html">立即预定</a>'
+    '{{else if ptype == "2"}}'
+	 	'<a class="next" id="pdtBook" href="orderForm_villa.html">立即预定</a>'
+    '{{else if ptype == "3"}}'
+	 	'<a class="next" id="pdtBook" href="orderForm_traffic.html">立即预定</a>'
+    '{{else if ptype == "4"}}'
+	 	'<a class="next" id="pdtBook" href="orderForm_amuse.html">立即预定</a>'
+    '{{/if}}';

//产品购买
var tmpl_prop = ''
+	'{{each}}'
+		'<li data-id="{{$value.id}}" data-price="{{$value.price}}">{{$value.carbrand}}，可坐{{$value.maxpeople}}人({{$value.hourCnt}}小时)</li>'
+   '{{/each}}';

var tmpl_counter = ''
+	'<h1 class="title">人数</h1>'
+	'<div class="counterWrap">'
+	'{{each}}'
+		'{{if $value.description}}'
+		'<div class="counterItem counterItemDsp f-box" data-info="{{$value.jsonstr}}">'
+     	'{{else}}'
+		'<div class="counterItem f-box" data-info="{{$value.jsonstr}}">'
+    	'{{/if}}'
+			'<div class="f-box f-flex">'
+				'<div class="fs30">{{$value.priceItem}}</div>'
+				'<div class="price f-box f-flex">'
+					'<label>¥ </label>'
+					'<input class="feeType" value="{{$value.price}}" readonly/>'
+				'</div>'
+			'</div>'
+			'<div class="counter f-box">'
+				'<div class="numBtn numReduce">-</div>'
+				'<input class="numField" value="{{$value.num || 0}}" data-min="0" readonly>'
+				'<div class="numBtn numAdd">+</div>'
+			'</div>'
+			'{{if $value.description}}'
+	 			'<div class="dsp f-toe">（{{$value.description}}）</div>'
+    		'{{/if}}'
+		'</div>'
+   '{{/each}}'
+   '</div>';

var tmpl_counterTraffic = ''
+	'<h1 class="title">车型选择</h1>'
+	'<div class="counterWrap">'
+	'{{each}}'
+		'<div class="counterItem counterItemDsp f-box" data-info="{{$value.jsonstr}}" data-max="5">'
+			'<div class="f-box f-flex">'
+				'<div class="fs30">{{$value.carbrand}}</div>'
+				'<div class="price f-box f-flex">'
+					'<label>¥ </label>'
+					'<input class="feeType" value="{{$value.price}}" readonly/>'
+				'</div>'
+			'</div>'
+			'<div class="counter f-box">'
+				'<div class="numBtn numReduce">-</div>'
+				'<input class="numField" value="{{$value.num || 0}}" data-min="0" readonly>'
+				'<div class="numBtn numAdd">+</div>'
+			'</div>'
+	 		'<div class="dsp f-toe">最多可坐{{$value.maxpeople}}人（{{$value.hourCnt}}小时）</div>'
+		'</div>'
+   '{{/each}}'
+   '</div>';

var tmpl_counterVilla = ''
+	'<h1 class="title">卧室规格</h1>'
+	'<div class="counterWrap">'
+	'{{each}}'
+		'<div class="counterItem counterItemDsp f-box" data-info="{{$value.jsonstr}}">'
+			'<div class="f-box f-flex">'
+				'<div class="fs30">{{$value.roomCnt}}卧室，可住{{$value.peopleCnt}}人</div>'
+				'<div class="price f-box f-flex">'
+					'<label>¥ </label>'
+					'<input class="feeType" value="{{$value.roomPrice}}" readonly/>'
+				'</div>'
+			'</div>'
+			'<div class="counter f-box">'
+				'<div class="numBtn numReduce">-</div>'
+				'<input class="numField" value="{{$value.num || 0}}" data-min="0" readonly>'
+				'<div class="numBtn numAdd">+</div>'
+			'</div>'
+		'</div>'
+   '{{/each}}'
+   '</div>';

var tmpl_counterHotel = ''
+	'<h1 class="title">酒店房型</h1>'
+	'<div class="counterWrap">'
+	'{{each}}'
+		'<div class="counterItem counterItem1" data-info="{{$value.jsonstr}}">'
+			'<div class="tname">{{$value.room_type_name}}</div>'
+			'{{if $value.description}}'
+			'<div class="desc">{{$value.description}}</div>'
+    		'{{/if}}'
+			'<div class="f-box f-flex">'
+				'<div class="price f-box f-flex">'
+					'<label>¥ </label>'
+					'<input class="feeType" value="{{$value.room_price}}" readonly/>'
+				'</div>'
+				'<div class="counter f-box">'
+					'<div class="numBtn numReduce">-</div>'
+					'<input class="numField" value="{{$value.num || 0}}" data-min="0" readonly>'
+					'<div class="numBtn numAdd">+</div>'
+				'</div>'
+			'</div>'
+		'</div>'
+   '{{/each}}'
+   '</div>';

var tmpl_orderConfirm = ''
+   '<h1 class="orderTitle">{{pdt_name}}</h1>'
+	'{{if pdt_desc}}'
+   	'<p class="orderSub">{{pdt_desc}}</p>'
+   '{{/if}}'
+   '<div class="box">'
+   	'<h5 class="tit">订单信息</h5>'
+   	'<ul class="infoContacts">'
+			'{{if time_start}}'
+   		'<li class="f-box">'
+				'{{if pdt_type == 1 || pdt_type == 2}}'
+   			'<label>入住日期：</label>'
+     			'{{else}}'
+   			'<label>出发日期：</label>'
+   			'{{/if}}'
+   			'<p class="f-flex">{{time_start}}'
+					'{{if time_detail}}'
+   				'&nbsp;&nbsp;{{time_detail}}'
+   				'{{/if}}'
+   			'</p>'
+   		'</li>'
+   		'{{/if}}'
+			'{{if time_end}}'
+   		'<li class="f-box">'
+				'{{if pdt_type == 2}}'
+   			'<label>退房日期：</label>'
+   			'<p class="f-flex">{{time_end}}</p>'
+   			'{{/if}}'
+   		'</li>'
+   		'{{/if}}'
+			'{{if time_days && pdt_type == 2}}'
+   		'<li class="f-box">'
+   			'<label>入住晚数：</label>'
+   			'<p class="f-flex">{{time_days}}晚</p>'
+   		'</li>'
+   		'{{/if}}'
+   		'<li class="f-box">'
+   			'<label>数量：</label>'
+   			'<div class="f-flex">'
+	 				'{{each order_data}}'
+					'{{if pdt_type == 2}}'
+   				'<p>{{$value.tname}} <i class="am-icon-times"></i> {{$value.num}}栋</p>'
+					'{{else if pdt_type == 3}}'
+   				'<p>{{$value.tname}} <i class="am-icon-times"></i> {{$value.num}}辆</p>'
+					'{{else}}'
+   				'<p>{{$value.tname}} <i class="am-icon-times"></i> {{$value.num}}人</p>'
+   				'{{/if}}'
+	 				'{{/each}}'
+   			'</div>'
+   		'</li>'
+   		'<li class="f-box">'
+   			'<label>订单备注：</label>'
+   			'<p class="f-flex">{{remark}}</p>'
+   		'</li>'
+   	'</ul>'
+   '</div>'
+   '<div class="box">'
+   	'<h5 class="tit">联系人信息</h5>'
+   	'<ul class="infoContacts">'
+   		'<li class="f-box">'
+   			'<label>姓名 ：</label>'
+   			'<p class="f-flex">{{linkman_name}}</p>'
+   		'</li>'
+   		'<li class="f-box">'
+   			'<label>手机 ：</label>'
+   			'<p class="f-flex">{{linkman_phone}}</p>'
+   		'</li>'
+   		'<li class="f-box">'
+   			'<label>邮箱 ：</label>'
+   			'<p class="f-flex">{{linkman_email}}</p>'
+   		'</li>'
+   	'</ul>'
+   '</div>';

var tmpl_orderTvr = ''
+	'{{if body.length <= 0}}'
+		'<div class="null">当前无随行人，请添加</div>'
+	'{{else}}'
+	'{{each body}}'
+		'<div class="infoTvr" data-info="{{$value.jsonstr}}">'
+			'<ul class="infoContacts">'
+				'<li class="f-box">'
+					'<label>真实姓名 ：</label>'
+					'<p class="f-flex">{{$value.realName}}</p>'
+				'</li>'
+				'<li class="f-box">'
+					'<label>出生日期 ：</label>'
+					'<p class="f-flex">{{$value.birthday | dateFormat:"yyyy-MM-dd"}}</p>'
+				'</li>'
+				'<li class="f-box">'
+					'<label>证件类型 ：</label>'
+					'{{if $value.cardType == 1}}'
+   					'<p class="f-flex">身份证</p>'
+					'{{else if $value.cardType == 2}}'
+						'<p class="f-flex">护照</p>'
+					'{{else if $value.cardType == 3}}'
+						'<p class="f-flex">军人证</p>'
+					'{{else if $value.cardType == 4}}'
+						'<p class="f-flex">回乡证</p>'
+					'{{else if $value.cardType == 5}}'
+						'<p class="f-flex">台胞证</p>'
+					'{{else if $value.cardType == 6}}'
+						'<p class="f-flex">港澳通行证</p>'
+					'{{else if $value.cardType == 7}}'
+						'<p class="f-flex">户口簿</p>'
+					'{{else if $value.cardType == 8}}'
+						'<p class="f-flex">出生证明</p>'
+					'{{else if $value.cardType == 9}}'
+						'<p class="f-flex">其他</p>'
+					'{{/if}}'
+				'</li>'
+				'<li class="f-box">'
+					'<label>证件号码 ：</label>'
+					'<p class="f-flex">{{$value.cardNumber}}</p>'
+				'</li>'
+			'</ul>'
+			'<div class="btn btnEdit"><i class="am-icon-edit"></i></div>'
+			'<div class="btn btnDele"><i class="am-icon-trash"></i></div>'
+		'</div>'
+   '{{/each}}'
+   '{{/if}}';

var tmpl_orderTvrEdit = ''
+	'{{if id}}'
+   	'<h5 class="tit titIco">修改随行人</h5>'
+	'{{else}}'
+   	'<h5 class="tit titIco">新增随行人</h5>'
+	'{{/if}}'
+	'<form id="form-verify-msg">'
+   	'<div class="am-form am-form-horizontal">'
+   		'<input type="hidden" class="am-form-field" name="id" value="{{id || 0}}">'
+   		'<div class="am-form-group">'
+   			'<label class="am-u-sm-3 am-form-label">真实姓名</label>'
+   			'<div class="am-u-sm-9">'
+   				'<input type="text" class="am-form-field" name="realName" value="{{realName}}" placeholder="请填写真实姓名" required data-validation-message="请填写真实姓名">'
+   			'</div>'
+   		'</div>'
+   		'<div class="am-form-group">'
+   			'<label class="am-u-sm-3 am-form-label">姓名拼音</label>'
+   			'<div class="am-u-sm-9">'
+   				'<input type="text" class="am-form-field" name="customerName" value="{{customerName}}" placeholder="请填写真实姓名英文全拼（大写）" required pattern="^[A-Z]+$" data-validation-message="请填写真实姓名英文全拼（大写）">'
+   			'</div>'
+   		'</div>'
+   		'<div class="am-form-group">'
+   			'<label class="am-u-sm-3 am-form-label">出生日期</label>'
+   			'<div class="am-u-sm-9">'
+   				'<input type="text" class="am-form-field" name="birthday" id="tvrBirthday" value="{{birthday | dateFormat:"yyyy-MM-dd"}}" placeholder="请填写出生日期" required data-validation-message="请填写出生日期" readonly>'
+   			'</div>'
+   		'</div>'
+   		'<div class="am-form-group">'
+   			'<label class="am-u-sm-3 am-form-label">证件类型</label>'
+   			'<div class="am-u-sm-9">'
+   				'<select class="am-form-field" name="cardType" required data-validation-message="请选择证件类型">'
+   					'<option value="1" {{if cardType == "1"}}selected{{/if}}>身份证</option>'
+   					'<option value="2" {{if cardType == "2"}}selected{{/if}}>护照</option>'
+   					'<option value="3" {{if cardType == "3"}}selected{{/if}}>军人证</option>'
+   					'<option value="4" {{if cardType == "4"}}selected{{/if}}>回乡证</option>'
+   					'<option value="5" {{if cardType == "5"}}selected{{/if}}>台胞证</option>'
+   					'<option value="6" {{if cardType == "6"}}selected{{/if}}>港澳通行证</option>'
+   					'<option value="7" {{if cardType == "7"}}selected{{/if}}>户口簿</option>'
+   					'<option value="8" {{if cardType == "8"}}selected{{/if}}>出生证明</option>'
+   					'<option value="9" {{if cardType == "9"}}selected{{/if}}>其他</option>'
+   				'</select>'
+   			'</div>'
+   		'</div>'
+   		'<div class="am-form-group">'
+   			'<label class="am-u-sm-3 am-form-label">证件号码</label>'
+   			'<div class="am-u-sm-9">'
+  					'<input type="text" class="am-form-field" name="cardNumber" value="{{cardNumber}}" placeholder="请填写证件号码" required data-validation-message="请填写证件号码">'
+   			'</div>'
+   		'</div>'
+   	'</div>'
+   	'<button type="submit" class="am-btn am-btn-warning am-btn-block">保存随行人</button>'
+   '</form>';

var tmpl_orderPay = ''
+   '<div class="box">'
+   	'<ul class="infoContacts">'
+   		'<li class="f-box">'
+   			'<label>商品名称：</label>'
+   			'<p class="f-flex">{{orderNm}}</p>'
+   		'</li>'
+   		'<li class="f-box">'
+   			'<label>订单总额：</label>'
+   			'<p class="f-flex">¥{{amount}}</p>'
+   			'<input type="hidden" id="payAmount" value="{{amount}}">'
+   		'</li>'
+			'{{if routeJson.time_start}}'
+   		'<li class="f-box">'
+				'{{if pdt_type == 1 || pdt_type == 2}}'
+   			'<label>入住日期：</label>'
+     			'{{else}}'
+   			'<label>出发日期：</label>'
+   			'{{/if}}'
+   			'<p class="f-flex">{{routeJson.time_start}}'
+					'{{if routeJson.time_detail}}'
+   				'&nbsp;&nbsp;{{time_detail}}'
+   				'{{/if}}'
+   			'</p>'
+   		'</li>'
+   		'{{/if}}'
+			'{{if routeJson.time_end && routeJson.pdt_type == 2}}'
+   		'<li class="f-box">'
+   			'<label>退房日期：</label>'
+   			'<p class="f-flex">{{routeJson.time_end | dateFormat:"yyyy-MM-dd"}}</p>'
+   		'</li>'
+   		'{{/if}}'
+   	'</ul>'
+   '</div>'
+   '<div class="detailBar detailBar1 f-box">'
+   	'<p class="total f-flex color2">¥{{amount}}</p>'
+   	'<a class="nextBtn" id="submitBtn">支付</a>'
+   '</div>';

//模板辅助方法
template.helper('dateFormat', function (date, format) {
	if(date){
		date = new Date(date);
	    var map = {
	        "M": date.getMonth() + 1, //月份 
	        "d": date.getDate(), //日 
	        "h": date.getHours(), //小时 
	        "m": date.getMinutes(), //分 
	        "s": date.getSeconds(), //秒 
	        "q": Math.floor((date.getMonth() + 3) / 3), //季度 
	        "S": date.getMilliseconds() //毫秒 
	    };
	    format = format.replace(/([yMdhmsqS])+/g, function(all, t){
	        var v = map[t];
	        if(v !== undefined){
	            if(all.length > 1){
	                v = '0' + v;
	                v = v.substr(v.length-2);
	            }
	            return v;
	        }
	        else if(t === 'y'){
	            return (date.getFullYear() + '').substr(4 - all.length);
	        }
	        return all;
	    });
	    return format;
	}
	else{
		return "";
	}
});